"""empty message

Revision ID: 869925d505cc
Revises: cfb6256d5978
Create Date: 2024-08-27 13:36:24.836761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869925d505cc'
down_revision = 'cfb6256d5978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_games', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('rank')

    # ### end Alembic commands ###
