"""empty message

Revision ID: 8e6f53ff2484
Revises: 869925d505cc
Create Date: 2024-08-28 04:22:37.031072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e6f53ff2484'
down_revision = '869925d505cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('ranks')

    with op.batch_alter_table('user_games', schema=None) as batch_op:
        batch_op.drop_column('rank')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ranks', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
