"""empty message

Revision ID: 269d0670f7ec
Revises: d1873b266400
Create Date: 2024-08-30 13:42:46.741184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269d0670f7ec'
down_revision = 'd1873b266400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_title', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('game_image_url', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_games', schema=None) as batch_op:
        batch_op.drop_column('game_image_url')
        batch_op.drop_column('game_title')

    # ### end Alembic commands ###
